// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Q7HnKyKxm27h9Vkxp0-XIhqKmBJBta8',
    appId: '1:173533741874:web:fc4e86b602f65f37338d2b',
    messagingSenderId: '173533741874',
    projectId: 'playhub-e2ca5',
    authDomain: 'playhub-e2ca5.firebaseapp.com',
    storageBucket: 'playhub-e2ca5.appspot.com',
    measurementId: 'G-RBZ74BZFP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucFIn5ArTyXAlPfTlIKQdRal3dfFXwcY',
    appId: '1:173533741874:android:ea9076ac3afebb7f338d2b',
    messagingSenderId: '173533741874',
    projectId: 'playhub-e2ca5',
    storageBucket: 'playhub-e2ca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_2Tak5hQUDPvEtreAi31XuEzcBuVqac',
    appId: '1:173533741874:ios:356466e9763703e6338d2b',
    messagingSenderId: '173533741874',
    projectId: 'playhub-e2ca5',
    storageBucket: 'playhub-e2ca5.appspot.com',
    iosBundleId: 'com.example.playhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_2Tak5hQUDPvEtreAi31XuEzcBuVqac',
    appId: '1:173533741874:ios:356466e9763703e6338d2b',
    messagingSenderId: '173533741874',
    projectId: 'playhub-e2ca5',
    storageBucket: 'playhub-e2ca5.appspot.com',
    iosBundleId: 'com.example.playhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Q7HnKyKxm27h9Vkxp0-XIhqKmBJBta8',
    appId: '1:173533741874:web:12a412459e9f680b338d2b',
    messagingSenderId: '173533741874',
    projectId: 'playhub-e2ca5',
    authDomain: 'playhub-e2ca5.firebaseapp.com',
    storageBucket: 'playhub-e2ca5.appspot.com',
    measurementId: 'G-VGJ0VB71TD',
  );
}
